name: Contentful Production Env Workflow

on:
  push:
    branches: [ master ]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install deps
        run: npm ci

      - name: Run contentful migrations against Production env
        run: npm run migrations
        env:
          CONTENTFUL_MANAGEMENT_API: ${{ secrets.CONTENTFUL_MANAGEMENT_API }}
          CONTENTFUL_SPACE_ID: jscbjpd3290q
          CONTENTFUL_ENVIRONMENT_ID: production

      - name: Build and Export static files
        run: npm run build
        env:
          TARGET_ENV: prod

      - name: Prepare Production website directory structure
        run: |
          mkdir contentful
          mv ./out/* ./contentful/

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'contentful'
          DEST_DIR: 'contentful/prod'
